project_id = "hilrxyokyjgjabfwmxnu"

[functions.customer-auth]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.send-email-brevo]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.generate-billing]
verify_jwt = false

[functions.send-sms-routemobile]
verify_jwt = false
